FROM golang:alpine3.20 AS builder

ENV GOOS=linux
ENV CGO_ENABLE=0
ENV GOARCH=amd64

WORKDIR /app

COPY go.mod go.sum ./
RUN go download

COPY . .

# RUN go build -o app /cmd/main.go
RUN go build -o app .

FROM alpine:3.14 AS production
RUN apk add --no-cach ca-certificates

COPY --from=builder app .

EXPOSE 8888

CMD ./app