services:
  app:
    container_name: e-document
    image: e-document
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - ~/.aws/:/root/.aws:ro
    links:
      - database
    depends_on:
      - database
    ports:
      - 8088:8088
    networks:
      - e-document-ci-cd-net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:127.0.0.1"
  database:
    container_name: e-document-mongodb
    image: mongo:latest
    hostname: mongo-edocdb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGODB_DB: ${MONGODB_DB}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    env_file:
      - .env
    ports:
      - ${MONGODB_PORT}:27017
    networks:
      - e-document-ci-cd-net
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - mongodb_data_smartapp:/data/db
volumes:
  db-data:
  mongodb_data_smartapp:

networks:
  e-document-ci-cd-net:
    driver: bridge