db:
  dbname: "smart_e_documents"
  port: 27019
#  uri: "mongodb://airsadmin:wPx7g4BvWrJd2022@127.0.0.1:27018/"
  uri: "mongodb+srv://acework2u:oBpnWK7cb4R8Jiwu@cluster0.tlketvu.mongodb.net/"

app:
  port: 8088
  clientOrigin: "*"
  ginMode : "debug"