name: Deploy to Application

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "PORT-${{ secrets.PORT }}" >> .env
      - name: login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t acework2u/e-document-service -f prod.Dockerfile .
      - name: Push image to docker hub
        run: docker push acework2u/e-document-service:latest
  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull acework2u/e-document-service:latest
      - name: Delete old container
        run: docker rm -f e-document-service
      - name: Run docker container
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          cd ~/e-document/  # แก้ไขให้ตรงกับ path ที่มี docker-compose.yml
          docker compose down              # หยุด container ที่รันอยู่
          docker compose pull              # ดึง image ล่าสุดจาก Docker Hub
          docker compose up -d             # รัน container ด้วย image ล่าสุด

#        run: docker run -d -p 8088:8088 --name e-document-service acework2u/e-document-service:latest
#        run: docker-compose -f docker-compose.prod.yml up -d
#        run: docker buildx build --platform=linux/amd64 -t e-document-service . --target production -f Dockerfile.production --no-cache



